.DEFAULT_GOAL := help
COMPOSE := docker compose

.PHONY: help up down logs build migrate revision seed ingest-once test lint fmt

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-16s\033[0m %s\n", $$1, $$2}'

up: ## Start the full stack
	$(COMPOSE) up -d

down: ## Stop the stack
	$(COMPOSE) down

logs: ## Tail logs
	$(COMPOSE) logs -f

build: ## Rebuild images
	$(COMPOSE) build

migrate: ## Apply DB migrations
	$(COMPOSE) run --rm api alembic upgrade head

revision: ## Create a new autogenerated migration (msg="...")
	$(COMPOSE) run --rm api alembic revision --autogenerate -m "$(msg)"

seed: ## Seed taxonomy + source registry
	$(COMPOSE) run --rm api python -m app.scripts.seed

ingest-once: ## Run all connectors a single time
	$(COMPOSE) run --rm worker python -m pipeline.run_once

test: ## Run backend tests
	$(COMPOSE) run --rm api pytest -q

lint: ## Lint backend
	$(COMPOSE) run --rm api ruff check .

fmt: ## Format backend
	$(COMPOSE) run --rm api ruff format .
